PacientesPuesto2 = createGroup west;
"3_T_Tan" createUnit [ SpawnPaciente2, PacientesPuesto2, "Paciente2 = this; doStop Paciente2"];
removeGoggles Paciente2;
Paciente2 addAction ["Eliminar paciente", "EntrenamientoMedico\EliminarPaciente.sqf"];
[Paciente2, selectRandom[0.3,0.5,0.7,0.9], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente2, selectRandom[0.3,0.5,0.7,0.9], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente2, selectRandom[0.3,0.5,0.7,0.9], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente2, selectRandom[0.3,0.5,0.7,0.9], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente2, selectRandom[0.3,0.5,0.7,0.9], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente2, selectRandom[0.3,0.5,0.7,0.9], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
hint 'Tu paciente esta listo.';
waitUntil {(!alive Paciente2)};
hint 'Tu paciente ha muerto';	
sleep 5;
deletevehicle Paciente2;