PacientesPuesto3 = createGroup west;
"B_Soldier_F" createUnit [ PacienteBot3, PacientesPuesto3, "Paciente3 = this; doStop Paciente3"];
removeGoggles Paciente3;
Paciente3 addAction ["<t color='#FF0000'> Eliminar paciente </t>", "EntrenamientoMedico\EliminarPaciente.sqf"];
[Paciente3, selectRandom[0.3,0.5,0.7,0.9], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente3, selectRandom[0.3,0.5,0.7,0.9], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente3, selectRandom[0.3,0.5,0.7,0.9], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente3, selectRandom[0.3,0.5,0.7,0.9], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente3, selectRandom[0.3,0.5,0.7,0.9], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente3, selectRandom[0.3,0.5,0.7,0.9], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
hint 'Tu paciente esta listo.';
waitUntil {(!alive Paciente3)};
hint 'Tu paciente ha muerto';	
sleep 5;
deletevehicle Paciente3;