PacientesPuesto1 = createGroup west;
"B_Soldier_F" createUnit [PacienteBot1, PacientesPuesto1, "Paciente1 = this; doStop Paciente1"];
removeGoggles Paciente1;
Paciente1 addAction ["<t color='#FF0000'> Eliminar paciente </t>", "EntrenamientoMedico\EliminarPaciente.sqf"];
[Paciente1, selectRandom[0.3,0.5,0.7,0.9], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente1, selectRandom[0.3,0.5,0.7,0.9], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente1, selectRandom[0.3,0.5,0.7,0.9], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente1, selectRandom[0.3,0.5,0.7,0.9], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente1, selectRandom[0.3,0.5,0.7,0.9], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[Paciente1, selectRandom[0.3,0.5,0.7,0.9], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
hint 'Tu paciente esta listo.';
waitUntil {(!alive Paciente1)};
hint 'Tu paciente ha muerto';	
sleep 5;
deletevehicle Paciente1;